language: python
python:
  - "2.7"

branches:
  only:
    - master 

services: postgresql

before_install:
  - sudo apt-get install postgis

before_script:
  - psql -c 'create database atlas;' -U postgres -T template_postgis

install:
  - pip install -r requirements.txt

script:
  - python manage.py test